In [1]:
import pandas as pd
import numpy as np

import seaborn as sns

import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

Using TensorFlow backend.


In [2]:
dataset = sns.load_dataset("iris")
dataset

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
9             4.9          3.1           1.5          0.1     setosa
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
13            4.3          3.0           1.1          0.1     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
16            5.4          3.9           1.3          0.4     setosa
17            5.1          3.5           1.4          0.3     setosa
18            5.7          3.8           1.7          0.3     setosa
19            5.1          3.8           1.5          0.3     setosa
20            5.4          3.4           1.7          0.2     setosa
21            5.1          3.7           1.5          0.4     setosa
22            4.6          3.6           1.0          0.2     setosa
23            5.1          3.3           1.7          0.5     setosa
24            4.8          3.4           1.9          0.2     setosa
25            5.0          3.0           1.6          0.2     setosa
26            5.0          3.4           1.6          0.4     setosa
27            5.2          3.5           1.5          0.2     setosa
28            5.2          3.4           1.4          0.2     setosa
29            4.7          3.2           1.6          0.2     setosa
..            ...          ...           ...          ...        ...
120           6.9          3.2           5.7          2.3  virginica
121           5.6          2.8           4.9          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
123           6.3          2.7           4.9          1.8  virginica
124           6.7          3.3           5.7          2.1  virginica
125           7.2          3.2           6.0          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
128           6.4          2.8           5.6          2.1  virginica
129           7.2          3.0           5.8          1.6  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
132           6.4          2.8           5.6          2.2  virginica
133           6.3          2.8           5.1          1.5  virginica
134           6.1          2.6           5.6          1.4  virginica
135           7.7          3.0           6.1          2.3  virginica
136           6.3          3.4           5.6          2.4  virginica
137           6.4          3.1           5.5          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica
139           6.9          3.1           5.4          2.1  virginica
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146

In [3]:
sns.set(style='ticks')
sns.pairplot(dataset.iloc[:,0:6], hue='species')

In [0]:
# Seperate the feature columns (first 4) from the labels columns (5th column)
x = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4].values

In [5]:
# Get the unique labels from the list with the help of numpy
species_names = np.unique(np.array(y))
species_names

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [6]:
# Convert the list to dictionary with indexes
species_names_dict = {k: v for v, k in enumerate(species_names)}
species_names_dict

{'setosa': 0, 'versicolor': 1, 'virginica': 2}

In [7]:
# 1 hot encode the labels since they are mutually exclusive
s = pd.DataFrame(y)
y_cat = pd.get_dummies(s)
y_cat.sample(5)

0_setosa  0_versicolor  0_virginica
26          1             0            0
18          1             0            0
75          0             1            0
143         0             0            1
97          0             1            0

In [8]:
# Split into train and test groups
## but first make the x (features) into pandas dataset
X = pd.DataFrame(x)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X.values, y_cat, test_size=0.25,random_state=42)
y_test

0_setosa  0_versicolor  0_virginica
73          0             1            0
18          1             0            0
118         0             0            1
78          0             1            0
76          0             1            0
31          1             0            0
64          0             1            0
141         0             0            1
68          0             1            0
82          0             1            0
110         0             0            1
12          1             0            0
36          1             0            0
9           1             0            0
19          1             0            0
56          0             1            0
104         0             0            1
69          0             1            0
55          0             1            0
132         0             0            1
29          1             0            0
127         0             0            1
26          1             0            0
128         0             0            1
131         0             0            1
145         0             0            1
108         0             0            1
143         0             0            1
45          1             0            0
30          1             0            0
22          1             0            0
15          1             0            0
65          0             1            0
11          1             0            0
42          1             0            0
146         0             0            1
51          0             1            0
27          1             0            0

In [9]:
# Softmax activation function because we work with 1-hot encoding labels
# The categorical_crossentropy is the one we use when working with sofmax
model = Sequential()
# 3 categories as output
# 4 input types
model.add(Dense(3,input_shape=(4,),activation='softmax'))
model.compile(Adam(lr=0.1),loss='categorical_crossentropy',metrics=['accuracy'])

W0618 18:20:40.767384 140000945817472 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0618 18:20:40.824145 140000945817472 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0618 18:20:40.834585 140000945817472 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0618 18:20:40.884329 140000945817472 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0618 18:20:40.901802 140000945817472 deprecation_wrappe

In [0]:
# Early stopping
from keras.callbacks import EarlyStopping
es = EarlyStopping(monitor='val_loss',min_delta=0.001,patience=5,verbose=1,mode='auto')

In [11]:
# Train the model
model.fit(X_train, y_train, validation_data=(X_test,y_test),callbacks=[es],epochs=500)

W0618 18:20:54.169243 140000945817472 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0618 18:20:54.220993 140000945817472 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Train on 112 samples, validate on 38 samples
Epoch 1/500
112/112 [==============================] - 1s 7ms/step - loss: 2.3717 - acc: 0.2589 - val_loss: 2.0938 - val_acc: 0.3158
Epoch 2/500
112/112 [==============================] - 0s 117us/step - loss: 1.6973 - acc: 0.3036 - val_loss: 1.1908 - val_acc: 0.2895
Epoch 3/500
112/112 [==============================] - 0s 104us/step - loss: 1.0397 - acc: 0.4286 - val_loss: 0.7569 - val_acc: 0.7105
Epoch 4/500
112/112 [==============================] - 0s 124us/step - loss: 0.7428 - acc: 0.6696 - val_loss: 0.5999 - val_acc: 0.7368
Epoch 5/500
112/112 [==============================] - 0s 111us/step - loss: 0.6003 - acc: 0.7321 - val_loss: 0.4852 - val_acc: 0.7895
Epoch 6/500
112/112 [==============================] - 0s 105us/step - loss: 0.5255 - acc: 0.7054 - val_loss: 0.4407 - val_acc: 0.8421
Epoch 7/500
112/112 [==============================] - 0s 106us/step - loss: 0.4870 - acc: 0.8482 - val_loss: 0.4064 - val_acc: 0.8684
Epoch 8/500


# Validate the results

In [12]:
# To see the predicted probabilty for each 
## of the 3 classes in the test group
y_pred = model.predict(X_test)
y_pred[:5]

array([[3.3709523e-03, 8.8122797e-01, 1.1540113e-01],
       [9.9661082e-01, 3.3892083e-03, 6.4445567e-11],
       [2.7638927e-10, 2.2715336e-04, 9.9977285e-01],
       [3.0610352e-03, 7.4114406e-01, 2.5579491e-01],
       [1.3688048e-03, 8.5464853e-01, 1.4398260e-01]], dtype=float32)

In [13]:
# Get the indices of the class which got the highest probability for each sample
y_pred = np.argmax(y_pred,axis=1)
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

In [14]:
y_actual = np.argmax(np.array(y_test),axis=1)
y_actual

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

In [0]:
from sklearn.metrics import classification_report

In [16]:
print(classification_report(y_actual, y_pred,target_names=species_names))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        15
  versicolor       1.00      0.91      0.95        11
   virginica       0.92      1.00      0.96        12

    accuracy                           0.97        38
   macro avg       0.97      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38



In [17]:
y_actual

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

In [18]:
species_names

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [19]:
from sklearn.metrics import confusion_matrix
# cm = confusion_matrix(y_actual,y_pred)
cm = confusion_matrix(species_names[y_actual], species_names[y_pred],species_names)
cm

array([[15,  0,  0],
       [ 0, 10,  1],
       [ 0,  0, 12]])

In [20]:
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure

plt.figure(figsize=(10,7))
sns.heatmap(cm,annot=True,xticklabels=True,yticklabels=True)
plt.xlabel('Predicted')
plt.ylabel('Actual')

Text(66.5, 0.5, 'Actual')

In [0]:
# https://gist.github.com/hitvoice/36cf44689065ca9b927431546381a3f7

def cm_analysis(y_true, y_pred, filename, labels, ymap=None, figsize=(10,10)):
    """
    Generate matrix plot of confusion matrix with pretty annotations.
    The plot image is saved to disk.
    args: 
      y_true:    true label of the data, with shape (nsamples,)
      y_pred:    prediction of the data, with shape (nsamples,)
      filename:  filename of figure file to save
      labels:    string array, name the order of class labels in the confusion matrix.
                 use `clf.classes_` if using scikit-learn models.
                 with shape (nclass,).
      ymap:      dict: any -> string, length == nclass.
                 if not None, map the labels & ys to more understandable strings.
                 Caution: original y_true, y_pred and labels must align.
      figsize:   the size of the figure plotted.
    """
    if ymap is not None:
        y_pred = [ymap[yi] for yi in y_pred]
        y_true = [ymap[yi] for yi in y_true]
        labels = [ymap[yi] for yi in labels]
    cm = confusion_matrix(y_true, y_pred, labels=labels)
    cm_sum = np.sum(cm, axis=1, keepdims=True)
    cm_perc = cm / cm_sum.astype(float) * 100
    annot = np.empty_like(cm).astype(str)
    nrows, ncols = cm.shape
    for i in range(nrows):
        for j in range(ncols):
            c = cm[i, j]
            p = cm_perc[i, j]
            if i == j:
                s = cm_sum[i]
                annot[i, j] = '%.1f%%\n%d/%d' % (p, c, s)
            elif c == 0:
                annot[i, j] = ''
            else:
                annot[i, j] = '%.1f%%\n%d' % (p, c)
    cm = pd.DataFrame(cm, index=labels, columns=labels)
    cm.index.name = 'Actual'
    cm.columns.name = 'Predicted'
    fig, ax = plt.subplots(figsize=figsize)
    sns.heatmap(cm, annot=annot, fmt='', ax=ax)
    plt.savefig(filename)

In [23]:
cm_analysis(y_actual, y_pred, 'figur1', [0,1,2], ymap={0:'setosa',1:'versicolor',2:'virginica'})
species_names

array(['setosa', 'versicolor', 'virginica'], dtype=object)

The model was able to correctly classify almost all of the samples in the test group. Not a simple task given the small number of samples and the fact that 2 of the species are indistinguishable to us as humans.